load-simulator {
  pool-target            = 1000
  pool-min               = 80
  call-timeout           = 5s
  report-every           = 5s
  reader-delay           = 30ms
  updater-delay          = 80ms
  deleter-delay          = 200ms
  lister-delay           = 1s
  creator-throttle-delay = 500ms
  creator-workers-per-10 = 1
  reader-workers-per-10  = 2
  updater-workers-per-10 = 1
}
